from __future__ import annotations

from typing import Any
from uuid import UUID

from sqlalchemy.ext.asyncio import AsyncSession

from agents.base import AgentRunContext
from agents.coordinator import CoordinatorAgent
from memory.story_bible import load_story_bible_context
from schemas.chapter import ChapterUpdate
from schemas.evaluation import EvaluationReport
from services.chapter_service import get_owned_chapter, update_chapter
from services.evaluation_service import evaluate_existing_chapter
from services.preference_service import (
    build_style_guidance,
    get_preference_learning_snapshot,
    get_or_create_user_preference,
    resolve_generation_preference_payload,
)
from services.project_service import PROJECT_PERMISSION_EDIT


async def build_generation_payload(
    session: AsyncSession,
    chapter_id: UUID,
    user_id: UUID,
) -> dict:
    chapter = await get_owned_chapter(
        session,
        chapter_id,
        user_id,
        permission=PROJECT_PERMISSION_EDIT,
    )
    context = await load_story_bible_context(session, chapter.project_id, user_id)
    preference = await get_or_create_user_preference(session, user_id)
    learning_snapshot = await get_preference_learning_snapshot(session, user_id)
    style_preferences = resolve_generation_preference_payload(
        preference,
        learning_snapshot,
    )

    return {
        "chapter_id": str(chapter.id),
        "project_id": str(chapter.project_id),
        "volume_id": str(chapter.volume_id) if chapter.volume_id is not None else None,
        "volume_title": chapter.volume.title if chapter.volume is not None else None,
        "volume_number": chapter.volume.volume_number if chapter.volume is not None else None,
        "branch_id": str(chapter.branch_id) if chapter.branch_id is not None else None,
        "branch_title": chapter.branch.title if chapter.branch is not None else None,
        "branch_key": chapter.branch.key if chapter.branch is not None else None,
        "branch_description": (
            chapter.branch.description if chapter.branch is not None else None
        ),
        "chapter_number": chapter.chapter_number,
        "chapter_title": chapter.title,
        "project_title": context.title,
        "genre": context.genre,
        "theme": context.theme,
        "tone": context.tone,
        "character_names": [item["name"] for item in context.characters[:12]],
        "location_names": [item["name"] for item in context.locations[:12]],
        "plot_threads": [item["title"] for item in context.plot_threads[:12]],
        "foreshadowing_count": len(context.foreshadowing),
        "timeline_count": len(context.timeline_events),
        "style_preferences": style_preferences,
        "style_learning_snapshot": learning_snapshot.model_dump(),
        "style_guidance": build_style_guidance(style_preferences, learning_snapshot),
    }


async def run_generation_pipeline(
    session: AsyncSession,
    *,
    chapter_id: UUID,
    user_id: UUID,
    task_id: str,
) -> dict[str, Any]:
    chapter = await get_owned_chapter(
        session,
        chapter_id,
        user_id,
        permission=PROJECT_PERMISSION_EDIT,
    )
    story_bible = await load_story_bible_context(session, chapter.project_id, user_id)
    base_payload = await build_generation_payload(session, chapter.id, user_id)

    coordinator = CoordinatorAgent()
    run_context = AgentRunContext(
        chapter_id=str(chapter.id),
        project_id=str(chapter.project_id),
        task_id=task_id,
        payload=base_payload,
    )
    response = await coordinator.run(
        run_context,
        {
            **base_payload,
            "story_bible": story_bible,
        },
    )
    if not response.success:
        raise RuntimeError(response.error or "Generation pipeline failed.")

    final_outline = response.data["outline"]
    final_content = response.data["content"]
    approval = response.data.get("approval")
    chapter_status = "review"
    if isinstance(approval, dict) and approval.get("approved") is False:
        chapter_status = "writing"

    updated_chapter = await update_chapter(
        session,
        chapter,
        ChapterUpdate(
            title=chapter.title or final_outline["title"],
            content=final_content,
            outline=final_outline,
            status=chapter_status,
            change_reason="Generated by coordinator pipeline",
            create_version=True,
        ),
        preference_learning_user_id=None,
    )
    report = await evaluate_existing_chapter(session, updated_chapter, user_id)

    return {
        "chapter_id": str(updated_chapter.id),
        "project_id": str(updated_chapter.project_id),
        "outline": final_outline,
        "content": final_content,
        "chapter_status": updated_chapter.status,
        "quality_metrics": updated_chapter.quality_metrics,
        "evaluation": _serialize_evaluation_report(report),
        "context_bundle": response.data.get("context_bundle"),
        "review": response.data.get("review"),
        "initial_review": response.data.get("initial_review"),
        "final_review": response.data.get("final_review"),
        "revision_focus": response.data.get("revision_focus"),
        "revision_plan": response.data.get("revision_plan"),
        "debate_summary": response.data.get("debate_summary"),
        "approval": approval,
        "agent_trace": run_context.trace,
        "revised": response.data.get("revised", False),
    }


def _serialize_evaluation_report(report: EvaluationReport) -> dict[str, Any]:
    return {
        "chapter_id": str(report.chapter_id),
        "overall_score": report.overall_score,
        "ai_taste_score": report.ai_taste_score,
        "metrics": report.metrics,
        "issues": [issue.model_dump() for issue in report.issues],
        "summary": report.summary,
        "context_snapshot": report.context_snapshot,
    }
