"""Pydantic schemas for API requests and responses.

This package intentionally uses lazy exports so importing `schemas.<module>`
does not eagerly pull in the entire schema graph and trigger circular imports.
"""

from __future__ import annotations

from importlib import import_module


_EXPORTS = {
    "LoginRequest": "schemas.auth",
    "RegisterRequest": "schemas.auth",
    "TokenResponse": "schemas.auth",
    "UserRead": "schemas.auth",
    "ORMModel": "schemas.base",
    "EmptyResponse": "schemas.base",
    "PaginatedResponse": "schemas.base",
    "CanonEntityRead": "schemas.canon",
    "CanonPluginSnapshotRead": "schemas.canon",
    "CanonSnapshotRead": "schemas.canon",
    "ChapterCreate": "schemas.chapter",
    "ChapterUpdate": "schemas.chapter",
    "ChapterRead": "schemas.chapter",
    "ChapterVersionRead": "schemas.chapter",
    "RollbackResponse": "schemas.chapter",
    "ChapterReviewCommentCreate": "schemas.chapter",
    "ChapterReviewCommentUpdate": "schemas.chapter",
    "ChapterReviewCommentRead": "schemas.chapter",
    "ChapterReviewAssignableMemberRead": "schemas.chapter",
    "ChapterReviewDecisionCreate": "schemas.chapter",
    "ChapterReviewDecisionRead": "schemas.chapter",
    "ChapterCheckpointCreate": "schemas.chapter",
    "ChapterCheckpointUpdate": "schemas.chapter",
    "ChapterCheckpointRead": "schemas.chapter",
    "ChapterReviewWorkspaceRead": "schemas.chapter",
    "ChapterSelectionRewriteRequest": "schemas.chapter",
    "ChapterSelectionRewriteResponse": "schemas.chapter",
    "DashboardProjectSummaryRead": "schemas.dashboard",
    "DashboardProjectTrendPointRead": "schemas.dashboard",
    "DashboardProjectQualityTrendRead": "schemas.dashboard",
    "DashboardRecentTaskRead": "schemas.dashboard",
    "DashboardOverviewRead": "schemas.dashboard",
    "EvaluationIssue": "schemas.evaluation",
    "EvaluationReport": "schemas.evaluation",
    "PreferenceLearningSignal": "schemas.preferences",
    "PreferenceLearningSnapshot": "schemas.preferences",
    "ActiveStyleTemplateRead": "schemas.preferences",
    "StyleTemplateRead": "schemas.preferences",
    "StyleTemplateApplyRequest": "schemas.preferences",
    "UserPreferenceUpdate": "schemas.preferences",
    "UserPreferenceRead": "schemas.preferences",
    "ChapterQualityMetricsSnapshot": "schemas.quality",
    "ProjectCreate": "schemas.project",
    "ProjectUpdate": "schemas.project",
    "ProjectRead": "schemas.project",
    "ProjectVolumeCreate": "schemas.project",
    "ProjectVolumeUpdate": "schemas.project",
    "ProjectVolumeRead": "schemas.project",
    "ProjectBranchCreate": "schemas.project",
    "ProjectBranchUpdate": "schemas.project",
    "ProjectBranchRead": "schemas.project",
    "ProjectStructureRead": "schemas.project",
    "ProjectSeedCharacter": "schemas.project",
    "ProjectBootstrapProfileUpdate": "schemas.project",
    "ProjectBootstrapProfileRead": "schemas.project",
    "ProjectBlueprintCharacter": "schemas.project",
    "ProjectBlueprintPlotThread": "schemas.project",
    "ProjectBlueprintForeshadowing": "schemas.project",
    "ProjectBlueprintTimelineBeat": "schemas.project",
    "ProjectBlueprintVolumePlan": "schemas.project",
    "ProjectChapterBlueprint": "schemas.project",
    "ProjectNovelBlueprintRead": "schemas.project",
    "ProjectBootstrapStoryStateSummaryRead": "schemas.project",
    "ProjectBootstrapRead": "schemas.project",
    "ProjectNextChapterCandidateRead": "schemas.project",
    "ProjectChapterGenerationDispatchRead": "schemas.project",
    "ProjectEntityGenerationDispatchRead": "schemas.project",
    "ProjectBlueprintGenerateRequest": "schemas.project",
    "ProjectCollaboratorCreate": "schemas.project",
    "ProjectCollaboratorUpdate": "schemas.project",
    "ProjectCollaboratorRead": "schemas.project",
    "ProjectCollaborationRead": "schemas.project",
    "CharacterItem": "schemas.project",
    "CharacterGenerationRequest": "schemas.project",
    "GeneratedCharacter": "schemas.project",
    "CharacterGenerationResponse": "schemas.project",
    "ItemGenerationRequest": "schemas.project",
    "GeneratedItem": "schemas.project",
    "ItemGenerationResponse": "schemas.project",
    "LocationGenerationRequest": "schemas.project",
    "GeneratedLocation": "schemas.project",
    "LocationGenerationResponse": "schemas.project",
    "FactionGenerationRequest": "schemas.project",
    "GeneratedFaction": "schemas.project",
    "FactionGenerationResponse": "schemas.project",
    "PlotThreadGenerationRequest": "schemas.project",
    "GeneratedPlotThread": "schemas.project",
    "PlotThreadGenerationResponse": "schemas.project",
    "WorldSettingItem": "schemas.project",
    "StoryBibleItemEntry": "schemas.project",
    "StoryBibleFactionEntry": "schemas.project",
    "LocationItem": "schemas.project",
    "PlotThreadItem": "schemas.project",
    "ForeshadowingItem": "schemas.project",
    "TimelineEventItem": "schemas.project",
    "StoryBibleOverrideItemRead": "schemas.project",
    "StoryBibleSectionOverrideRead": "schemas.project",
    "StoryBibleScopeRead": "schemas.project",
    "StoryBibleRead": "schemas.project",
    "StoryBibleUpdate": "schemas.project",
    "StoryBibleBranchItemUpsert": "schemas.project",
    "StoryBibleBranchItemDelete": "schemas.project",
    "StoryBibleVersionRead": "schemas.story_bible_version",
    "StoryBibleVersionList": "schemas.story_bible_version",
    "StoryBiblePendingChangeCreate": "schemas.story_bible_version",
    "StoryBiblePendingChangeRead": "schemas.story_bible_version",
    "StoryBiblePendingChangeList": "schemas.story_bible_version",
    "StoryBibleApprovalRequest": "schemas.story_bible_version",
    "StoryBibleRollbackRequest": "schemas.story_bible_version",
    "ConflictCheckRequest": "schemas.story_bible_version",
    "ConflictCheckResult": "schemas.story_bible_version",
    "StoryCharacterCreate": "schemas.story_engine",
    "StoryCharacterUpdate": "schemas.story_engine",
    "StoryCharacterRead": "schemas.story_engine",
    "StoryForeshadowCreate": "schemas.story_engine",
    "StoryForeshadowUpdate": "schemas.story_engine",
    "StoryForeshadowRead": "schemas.story_engine",
    "StoryItemCreate": "schemas.story_engine",
    "StoryItemUpdate": "schemas.story_engine",
    "StoryItemRead": "schemas.story_engine",
    "StoryWorldRuleCreate": "schemas.story_engine",
    "StoryWorldRuleUpdate": "schemas.story_engine",
    "StoryWorldRuleRead": "schemas.story_engine",
    "StoryTimelineMapEventCreate": "schemas.story_engine",
    "StoryTimelineMapEventUpdate": "schemas.story_engine",
    "StoryTimelineMapEventRead": "schemas.story_engine",
    "StoryOutlineCreate": "schemas.story_engine",
    "StoryOutlineUpdate": "schemas.story_engine",
    "StoryOutlineRead": "schemas.story_engine",
    "StoryChapterSummaryCreate": "schemas.story_engine",
    "StoryChapterSummaryUpdate": "schemas.story_engine",
    "StoryChapterSummaryRead": "schemas.story_engine",
    "StoryKnowledgeVersionRead": "schemas.story_engine",
    "StoryKnowledgeRollbackResponse": "schemas.story_engine",
    "StorySearchResultRead": "schemas.story_engine",
    "StoryCharacterGraphNode": "schemas.story_engine",
    "StoryCharacterGraphEdge": "schemas.story_engine",
    "StoryCharacterGraphRead": "schemas.story_engine",
    "StoryEngineProjectInfo": "schemas.story_engine",
    "StoryEngineWorkspaceRead": "schemas.story_engine",
    "StoryEngineRoleCatalogRead": "schemas.story_engine",
    "StoryEngineModelOptionRead": "schemas.story_engine",
    "StoryEngineRoleRoutingRead": "schemas.story_engine",
    "StoryEngineRoutingPresetRead": "schemas.story_engine",
    "StoryEnginePresetSummaryRead": "schemas.story_engine",
    "StoryEnginePresetCatalogRead": "schemas.story_engine",
    "StoryEngineModelRoutingRead": "schemas.story_engine",
    "StoryEngineRouteUpdate": "schemas.story_engine",
    "StoryEngineModelRoutingUpdateRequest": "schemas.story_engine",
    "StoryEngineIssueRead": "schemas.story_engine",
    "StoryEngineAgentReportRead": "schemas.story_engine",
    "OutlineStressTestRequest": "schemas.story_engine",
    "OutlineStressTestResponse": "schemas.story_engine",
    "RealtimeGuardRequest": "schemas.story_engine",
    "RealtimeGuardResponse": "schemas.story_engine",
    "FinalOptimizeRequest": "schemas.story_engine",
    "FinalOptimizeResponse": "schemas.story_engine",
    "ChapterStreamGenerateRequest": "schemas.story_engine",
    "ChapterStreamEventRead": "schemas.story_engine",
    "StoryOutlineImportItem": "schemas.story_engine",
    "StoryBulkImportPayload": "schemas.story_engine",
    "StoryImportTemplateRead": "schemas.story_engine",
    "StoryBulkImportRequest": "schemas.story_engine",
    "StoryBulkImportResponse": "schemas.story_engine",
    "StoryGeneratedCandidateAcceptRequest": "schemas.story_engine",
    "StoryGeneratedCandidateAcceptResponse": "schemas.story_engine",
}

__all__ = sorted(_EXPORTS)


def __getattr__(name: str):
    module_name = _EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module 'schemas' has no attribute {name!r}")
    module = import_module(module_name)
    value = getattr(module, name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
