export const COPY = {
  button: {
    startChapter: "开始这一章",
    resumeDraft: "帮我续一段",
    saveContent: "收下这段",
    usePreviousVersion: "用前一个版本",
    discardVersion: "不用这个版本",
    viewHistory: "看看之前写过什么",
    rewriteWithDirection: "按这个方向重写",
    createProject: "开一本新书",
    applyStyleTemplate: "套用这个手感",
    submitForReview: "送审",
    adoptSuggestion: "采纳",
    retry: "再试一次",
    refresh: "刷新看看",
    goToWorkspace: "去创作空间",
    continueWriting: "继续写",
    confirmFinalDraft: "锁定终稿",
    clearDraft: "清掉这一稿",
    recoverDraft: "恢复续写稿",
    generateOutline: "生成章纲",
    startWorldBuilding: "开始构建世界观",
    saveAndContinue: "保存并继续",
    skip: "跳过",
    nextStep: "下一步",
    previousStep: "上一步",
  },

  empty: {
    noChapter: "还没有正文，先来起个头吧",
    noOutline: "还没有章纲，先来规划一下这一章写什么？",
    noBible: "设定本还是空的，先来搭好世界观",
    noStyleTemplate: "还没有锁定手感，去风格中心挑一个？",
    noHistory: "这是第一个版本，写下去就有历史了",
    noCollaborators: "还没有其他伙伴，可以邀请合作者",
    noProjects: "还没有书，来开一本新书吧",
    noChapters: "这一卷还没有章节，来起个头吧",
    noDraft: "还没有续写稿，让 AI 帮你写一段？",
  },

  loading: {
    thinking: "正在构思中…",
    writing: "AI 正在写下一段…",
    generatingOutline: "AI 正在规划章节结构…",
    saving: "正在收下…",
    loadingBible: "正在翻设定本…",
    generating: "正在生成中…",
    processing: "正在处理中…",
  },

  success: {
    saved: "已经收下了",
    contentOnHand: "这一段已经在你手上了",
    versionLocked: "版本已锁定，这一版不会再变了",
    finalDraftLocked: "终稿已锁定，这一章完成了",
    styleTemplateApplied: "这套手感已经套进整本书了",
    bibleUpdated: "设定本已更新",
    projectCreated: "新书已创建，开始写吧",
    outlineGenerated: "章纲已生成，来看看这一章怎么写",
    worldBuildingComplete: "世界观已搭好，可以开始写大纲了",
  },

  error: {
    networkError: "网络好像不太顺，试试再来一次？",
    generationFailed: "这次没写顺，试试调整下章纲再来？",
    saveFailed: "收下的时候出了点小状况，没有丢内容，再试一次？",
    chapterNotFound: "这一章不见了，刷新看看？",
    noWritingIntent: "先说说这一章想写什么，AI 才知道怎么帮你",
    outlineGenerationFailed: "章纲没生成顺，点点再来一次？",
    projectNotFound: "这本书找不到了，去书架看看？",
    unauthorized: "这里进不去，登录看看？",
    rateLimited: "写得太快了，歇一秒再继续？",
    unknown: "出了点小状况，刷新试试？",
  },

  hint: {
    outlineInput: "写一段话，描述这一章要发生什么",
    writingIntentInput: "用一两句话说说这一章的核心目标，比如'主角第一次战斗'",
    resumeHint: "告诉 AI 你想要什么，比如'再来一段打斗'",
    chapterCountInput: "告诉 AI 你计划写多少章，帮助它规划节奏",
    styleTemplateSelect: "挑一个和你想要的文风最像的，AI 会按这个感觉来写",
    chapterNameInput: "给这一章起个名字，比如'初入江湖'",
    protagonistInput: "你的主角是什么人？有什么独特之处？",
    worldBackgroundInput: "请问，这是一个什么样的世界？",
  },

  worldBuilding: {
    step1Title: "世界基底",
    step1Question: "请问，这是一个什么样的世界？",
    step2Title: "物理世界",
    step2Question: "这个世界的物理法则和自然环境有什么特别之处？",
    step3Title: "力量体系",
    step3Question: "这个世界存在什么样的力量体系或超凡能力？",
    step4Title: "社会结构",
    step4Question: "这个世界的社会结构、势力划分和主要矛盾是什么？",
    step5Title: "主角定位",
    step5Question: "你的主角是什么人？有什么独特之处？",
    step6Title: "核心冲突",
    step6Question: "故事的核心冲突是什么？主角面临的主要挑战是什么？",
    step7Title: "世界细节",
    step7Question: "还有什么想要补充的世界设定吗？如历史、文化、地理等。",
    step7Optional: "（可不填）",
    step8Title: "风格偏好",
    step8Question: "你希望故事的整体风格是什么样的？轻松、压抑、热血？",
    step8Optional: "（可不填）",
    completing: "正在收尾世界观…",
    complete: "世界观已搭建完成",
  },

  storyRoom: {
    enterWritingIntent: "说说这一章想写什么",
    writingIntentPlaceholder: "用一两句话描述这一章的核心情节，比如：主角林舟第一次和妖兽战斗…",
    generateOutline: "生成章纲",
    generateFirstDraft: "起稿",
    sectionOutline: "章纲",
    sectionDraft: "正文",
    sectionReview: "精修台",
    draftResume: "续写稿",
    versionHistory: "历史版本",
    styleControl: "文风与写法",
    recentActivity: "最近动态",
    collaboratorActive: "有人在写这一章",
  },

  review: {
    aiFeedback: "AI 反馈理解",
    aiFeedbackHint: "输入修改意见，AI 生成结构化修改指令",
    feedbackPlaceholder: "比如：第三章主角性格太软了，战斗场景不够燃，需要增加反转…",
    generateFeedback: "生成修改指令",
    regenerating: "重写中…",
    regenerateWithFeedback: "基于指令重写章节",
    rewriteSelection: "重写这段",
    selectTextHint: "先选中一段文字，再点这里重写",
    paragraphRewrite: "段落改写",
    checkpoint: "确认点",
    addCheckpoint: "添加确认点",
    comment: "批注",
    addComment: "添加批注",
    resolveComment: "已处理",
    rollback: "回到这个版本",
    finalDraft: "终稿",
    lockFinalDraft: "锁定终稿",
    draftVersion: "草稿",
    currentVersion: "当前版本",
  },

  dashboard: {
    myBooks: "我的书架",
    recentProjects: "最近在写的",
    createNew: "开一本新书",
    noRecentProjects: "最近还没写字，去写书吧",
    totalWords: "累计字数",
    chapters: "章节数",
    lastActive: "最近写作",
    quality: "质量评分",
    writingStreak: "连续写作",
    days: "天",
  },

  project: {
    settings: "项目设置",
    collaborators: "协作者",
    bible: "设定本",
    worldBuilding: "世界观",
    outline: "章纲",
    chapters: "章节",
    generations: "素材库",
    quality: "质量",
    style: "风格中心",
    recentActivity: "最近动态",
  },
} as const;

export type CopyKey = typeof COPY;
